### ISSUE TITLE
Generator doesn't work with freezed models

### ISSUE THREAD

**Issue by awaik** [objectbox/objectbox-dart#414] opened 2022-04-29 20:11 UTC
According to the documentation and closed issue https://github.com/objectbox/objectbox-dart/issues/229 Objectbox supports generating with freezed.
But if I copy-paste the example from the docs - nothing happens. All classes are ok, but with freezed - nothing generated.

### Basic info (please complete the following information):

- ObjectBox version: 1.4.1
- Flutter/Dart SDK: Flutter 2.10.4 • channel stable • Dart 2.16.2
- Null-safety enabled: yes
- Reproducibility: always
- OS: macOs BigSur 
- Device/Emulator: IphoneX

### Steps to reproduce

Just copy-paste an example and run 
`packages pub run build_runner build --delete-conflicting-outputs`

```
part 'test_person.freezed.dart';

@Freezed()
class Person with _$Person {
  @Entity(realClass: Person)
  factory Person({
    @Id(assignable: true) int? id,
    String? name,
    int? age,
  }) = _Person;
}

```

### Expected behavior

Should generate ModelEntity in objectbox.g.dart

**Comment by greenrobot-team** [comment] 2022-05-02 09:04
I assume you have set up ObjectBox as documented at https://docs.objectbox.io/getting-started?

If so, please submit a full project that we can reproduce this with.

**Comment by awaik** [comment] 2022-05-02 19:28
You are right. With clean project it works.

For those who might be experienced the same bug - the reason is in 
`auto_route_generator: ^3.2.3` (tried different versions, the result is the same)
After commenting it, starts to generate the entities with freezed.
I haven't figured out the reason, no any errors in the console, just stops to generate.

**Comment by greenrobot-team** [comment] 2022-05-03 06:07
@awaik Weird, if you ever find out if this is because something ObjectBox can improve, let us know! Closing this then!

**Closed by greenrobot-team** 2022-05-03 06:07 UTC
Labels: more info required

**Comment by Derb456** [comment] 2022-08-13 16:21
I got exactly the same issue and found no way to work around it.

I tried limiting the scanned directories for both generatos in build.yaml
Not even disabling the auto_route_generator in the build.yaml worked.

At the moment auto_route_generator is added to pubspec.yaml, objectbox just stops generating freezed classes. It doesn't even appear in the build --verbose output anymore.

**Comment by EvgeniShmakov** [comment] 2022-08-20 13:11
In my case it happens because objectbox runs BEFORE freezed.
You can verify it here: .dart_tool/build/entrypoint/build.dart
After manual order changing it works if you run this dart file manually.
But build_runner re-creates the old order.
So far I did not find how to order builders.
