### ISSUE TITLE
findIds+get result set is not equal to find results

### ISSUE THREAD

**Issue by softkot** [objectbox/objectbox-dart#177] opened 2021-01-25 11:03 UTC
Starting with releases higher than objectbox: 0.8.0 i experience an issue with using findIds method which is widly used within the project. 

0.8.0 version works just fine and returns properly ids array. Versions higher than 0.8.0 (confirmed on latest 0.10.0 as well) returns an array that randomly can contains zero or other wrong values which feeding into get(id) method produce _ObjectBoxException: 10002 Illegal ID value_

That prevents me to follow the stable release version and stuck on 0.8.0

**Comment by vaind** [comment] 2021-01-25 13:52
Hmm, can't see what have changed there... can you please provide a minimal reproducible example? Maybe forking objectbox-dart and adding a test case to `box_test.dart` would work for you.

**Comment by softkot** [comment] 2021-01-25 16:54
It can take a while, but i will try to do a test_case

**Comment by vaind** [comment] 2021-01-28 15:59
Also, what platform does this happen on?

**Comment by vaind** [comment] 2021-03-12 14:00
Unfortunately, I have to close this due to the lack of details and no reproducible example. Feel free to reopen when you have more details or ideas how to reproduce.

**Closed by vaind** 2021-03-12 14:00 UTC
Labels: bug
