### ISSUE TITLE
Invalid argument(s): Failed to lookup symbol (undefined symbol: obx_version_is_at_least )

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#346] opened 2021-12-06 16:39 UTC
After updating to latest version I am getting the above error.

**Comment by greenrobot-team** [comment] 2021-12-07 11:10
Can you please share more about your setup? Filling out the issue template would help.

If this is for a Dart CLI app, this may be caused by an outdated objectbox-c library.

If this is a Flutter app, check if your project overrides any Android or iOS dependencies and update them to the latest versions.

**Comment by vaind** [comment] 2021-12-18 08:07
Duplicate of #252

**Closed by vaind** 2021-12-18 08:07 UTC
Labels: bug, more info required
