### ISSUE TITLE
How to create BaseEntity in Flutter

### ISSUE THREAD

**Issue by huynn0105** [objectbox/objectbox-dart#471] opened 2022-09-23 08:37 UTC
i can't create BaseEntity in Futter, 
i read https://docs.objectbox.io/advanced/entity-inheritance but i don't see it.

**Comment by techouse** [comment] 2022-09-23 08:50
Duplicate of https://github.com/objectbox/objectbox-dart/issues/249

**Closed** 2022-10-04 12:21 UTC
Labels: duplicate, enhancement
