### ISSUE TITLE
loading library issue.

### ISSUE THREAD

**Issue by richard457** [objectbox/objectbox-dart#352] opened 2021-12-18 05:44 UTC
![Capture](https://user-images.githubusercontent.com/8529700/146630769-00c7f6d0-bf16-4fae-becd-dff6f5ea94fd.PNG)

even when an error shows after the app keeps working but it is annoying to see this bug every time I refresh the app.

**Comment by vaind** [comment] 2021-12-18 08:08
Duplicate of #252

**Closed by vaind** 2021-12-18 08:08 UTC
Labels: bug
