### ISSUE TITLE
 Entity Inheritance #249 can not 👍  at the top ⬆️

### ISSUE THREAD

**Issue by navyzhou926** [objectbox/objectbox-dart#534] opened 2023-05-04 02:20 UTC
https://github.com/objectbox/objectbox-dart/issues/249

Entity Inheritance is very important and usefull for developers. Is there any plans for entity inheritance please

**Comment by greenrobot-team** [comment] 2023-05-08 06:30
Duplicate of #249.

I unlocked the conversation, you should be able to thumbs up again.

**Closed by greenrobot-team** 2023-05-08 06:30 UTC
Labels: bug
