### ISSUE TITLE
Dart Entity Inheritance. Also Dart Entity MIXIN support

### ISSUE THREAD

**Issue by natgross** [objectbox/objectbox-dart#289] opened 2021-07-29 20:25 UTC
The problem I want to solve: Many common fields in many entities.

If I had inheritance in Dart (when?), no problem. Base class has all the common fields and all entities extend it.

But also should be able to accomplish this with a mixin class. Any trick to accomplish this?

**Comment by vaind** [comment] 2021-07-30 06:56
Duplicate of #249, please continue in the original issue

**Closed by vaind** 2021-07-30 06:56 UTC
Labels: enhancement
