### ISSUE TITLE
Update entity by @Index or @Unique value

### ISSUE THREAD

**Issue by RTrackerDev** [objectbox/objectbox-dart#158] opened 2020-12-01 14:12 UTC
Please add the ability to update the entity not by `@Id` but also by `@Index` or `@Unique` property when use `put` or `putMany` methods. This is required when using a `String` as an identifier.

**Comment by greenrobot-team** [comment] 2020-12-01 14:21
I don't see the use case, can you elaborate? E.g. when you use `put` or `putMany` and you already have objects they have an `@Id`. If you put new objects, they will get an `@Id` assigned.

Maybe you are looking for the `@Unique` annotation that prevents inserting multiple objects with the same property value?

**Comment by RTrackerDev** [comment] 2020-12-01 14:44
I need not to be throw exception with such field, just to update it. Because the server uses strings as an identifier.

**Comment by vaind** [comment] 2020-12-01 14:58
Do you mean sth. like [INSERT ON DUPLICATE KEY UPDATE](https://mariadb.com/kb/en/insert-on-duplicate-key-update/) in MariaDB?

**Comment by RTrackerDev** [comment] 2020-12-01 15:16
> Do you mean sth. like [INSERT ON DUPLICATE KEY UPDATE](https://mariadb.com/kb/en/insert-on-duplicate-key-update/) in MariaDB?

I think yes

**Comment by vaind** [comment] 2021-08-17 07:15
duplicate of #297 which is newer but has more specific details and context

**Closed by vaind** 2021-08-17 07:15 UTC
Labels: enhancement, needs more interest
