### ISSUE TITLE
Dependecy conflict  due outdated dependecies

### ISSUE THREAD

**Issue by pMertDogan** [objectbox/objectbox-dart#457] opened 2022-08-18 16:44 UTC
Hi,

Unable to use objectbox with freezed due outdated dependencies. Is it possible to update them?

  build_runner: 
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0
  objectbox_generator: any

Because objectbox_generator <0.13.0+1 depends on source_gen ^0.9.0 and objectbox_generator >=0.13.0-nullsafety.0 <1.2.0 depends on analyzer ^1.1.0, objectbox_generator <1.2.0 requires source_gen ^0.9.0 or analyzer ^1.1.0.
And because objectbox_generator >=1.2.0 <1.4.0-dev.1 depends on analyzer >=1.1.0 <3.0.0 and objectbox_generator >=1.4.0-dev.1 depends on analyzer >=1.1.0 <4.0.0, every version of objectbox_generator requires analyzer >=1.1.0 <4.0.0 or source_gen ^0.9.0.
And because freezed >=1.0.1 depends on source_gen ^1.2.0 and freezed >=2.0.5 depends on analyzer ^4.2.0, freezed >=2.0.5 is incompatible with objectbox_generator.
So, because p763_quiz depends on both freezed ^2.1.0 and objectbox_generator any, version solving failed.
pub get failed (1; So, because p763_quiz depends on both freezed ^2.1.0 and objectbox_generator any, version solving failed.)
exit code 1

**Comment by arthurjgs** [comment] 2022-08-19 07:28
Same issue with auto_route_generator: ^5.0.0
Please update your depencies.

**Comment by greenrobot-team** [comment] 2022-08-22 12:21
Thanks! It appears #443 is a duplicate of this (a workaround is also mentioned there), closing this then.

**Closed by greenrobot-team** 2022-08-22 12:21 UTC
Labels: bug
