### ISSUE TITLE
ObjectBoxException:objectputfailed:10101Couldnotcommittx

### ISSUE THREAD

**Issue by DuJerry** [objectbox/objectbox-dart#325] opened 2021-10-26 09:53 UTC
### Basic info (please complete the following information):

- ObjectBox version: [0.12.2]
- Flutter/Dart SDK: 
  Flutter 1.22.6 • channel unknown • unknown source
  Framework • revision 9b2d32b605 (9 个月前) • 2021-01-22 14:36:39 -0800
  Engine • revision 2f0af37152
  Tools • Dart 2.10.5
- Null-safety enabled: [no]
- Reproducibility: [Occasionally]
- OS: [Android 10]
- Device/Emulator: [e.g. Galaxy S20]

When I use put() to store objects, I occasionally get this error. I want to know why this error occurs?

**Comment by greenrobot-team** [comment] 2021-11-02 10:21
Thanks! Can you possibly post the complete error message / stack trace? And if possible a snippet of the code that does the put so we can try to reproduce this or spot any issues.

**Comment by greenrobot-team** [comment] 2021-12-20 14:07
Closing because this issue is missing details. Feel free to comment with additional details and we can re-open it.

**Closed by greenrobot-team** 2021-12-20 14:07 UTC
Labels: bug, more info required
