### ISSUE TITLE
objectbox_flutter_libs_plugin.dll is flagged as infected

### ISSUE THREAD

**Issue by Mangiang** [objectbox/objectbox-dart#462] opened 2022-08-25 22:24 UTC
### Basic info:

- ObjectBox version: ^1.6.2
- Fluttert SDK: 3.0.5
- Null-safety enabled: yes
- Reproducibility: always
- OS: Windows 10

Additionally, you can choose to provide more details, e.g. the output of:

- [Repository to help reproduce](https://github.com/Mangiang/objectbox_infection_issue)
  - it is a brand new project with only the folloing files modified `pubspec.yml`, `generated_plugin_registrant.cc`, `generated_plugin_registrant.cmake` (see commits on the repo)
- [VirusTotal report](https://www.virustotal.com/gui/file/e44b13cf2eb654ecc2e71838572b4de3faa6777620f11438c829e9d8f349cf4a?nocache=1)

### Steps to reproduce

1. Clone the repository
2. Execute `flutter pub get`
3. Execute `flutter run -d windows`
4. If no antivirus flagged `objectbox_flutter_libs_plugin.dll`, try to send it to VirusTotal for analysis
5. Notice either the Antivirus or VirusTotal report about a `Gen:Variant.Tedy.191479`

### Expected behavior

No virus should be detected when executing a brand new project using that package.

### Code

If applicable, add code to help explain your problem.

- `pubspec.yaml`
```yml
name: objectbox_infection_issue
description: Replication for Objectbox infection flagging issue

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  objectbox: ^1.6.2
  objectbox_flutter_libs: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  objectbox_generator: ^1.6.2

flutter:
  uses-material-design: true
```

### Logs, stack traces

[VirusTotal report](https://www.virustotal.com/gui/file/e44b13cf2eb654ecc2e71838572b4de3faa6777620f11438c829e9d8f349cf4a?nocache=1)

Bitdefender Report:
![image](https://user-images.githubusercontent.com/9913715/186779127-c361ade7-7a9b-43b0-93e4-70bee46f730a.png)

**Comment by MerijnHendriks** [comment] 2022-08-25 22:37
I managed to reproduce the issue, this is pretty concerning

**Comment by greenrobot-team** [comment] 2022-08-29 08:16
Thanks! However, `objectbox_flutter_libs_plugin.dll` (from `build/windows/plugins/objectbox_flutter_libs/Debug/objectbox_flutter_libs_plugin.dll`) is not shipped with our library. It is built by Flutter tools on your system. I would suggest to check your system for malware and maybe re-install a clean copy of Flutter.

E.g. when building our relations example with Flutter 3.0.5 the file is without issues: https://www.virustotal.com/gui/file/adba79f0011423eae56c0498c8ae8c0799e61ecb2dbee9faed5ab857120572d2

**Comment by Mangiang** [comment] 2022-09-01 16:37
Hello,
Thank you for taking the time to check that issue. Are you able to reproduce it a brand new reporitory ? [Here is the one I created](https://github.com/Mangiang/objectbox_infection_issue)

Bitdefender and Malwarebytes (both up to date) are not able to find any malware on my computer, but they both actually flag `objectbox_flutter_libs_plugin.dll` as a threat 
![image](https://user-images.githubusercontent.com/9913715/187966776-8b71c7f3-68c0-4ab4-b1d6-6aa8c3eec821.png)
And my Windows tools are up to date

The tag is an interesting one, how should I go about it ?

**Comment by MerijnHendriks** [comment] 2022-09-01 17:22
I took the additional step of fully reinstalling windows 10 ltsc on a device permanently disconnected from the internet, transfered the required files onto a newly bought usb from my office pc at work (IT dep. confirmed no virusses on there) and rebuild and test. Still the same issue. Im not sure what else I could do to make the test environment more clean.

**Comment by Mangiang** [comment] 2022-10-04 16:14
Hello,

Thank you for taking the time to investigate further. I upgraded my flutter installation and it seems like the issue got resolved between when I reported it and now (here is the [virus total report](https://www.virustotal.com/gui/file/ab8502ebdbfe9784a2c5f98fcf5312de6f75082774326a3fca8888f9271d862b?nocache=1))

Here is my `flutter doctor -v` output
```
[√] Flutter (Channel stable, 3.3.3, on Microsoft Windows [version 10.0.19043.2006], locale fr-FR)
    • Flutter version 3.3.3 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18a827f393 (6 days ago), 2022-09-28 10:03:14 -0700
    • Engine revision 5c984c26eb
    • Dart version 2.18.2
    • DevTools version 2.15.0

[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at C:\Users\mangi\AppData\Local\Android\sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = C:\Users\mangi\AppData\Local\Android\sdk
    • Java binary at: D:\Users\mangi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8815526\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.3.5)
    • Visual Studio at H:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.3.32922.545
    • Windows 10 SDK version 10.0.20348.0

[√] Android Studio (version 2021.2)
    • Android Studio at D:\Users\mangi\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\212.5712.43.2112.8815526
    • Flutter plugin version 69.0.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+7-b1504.28-7817840)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [version 10.0.19043.2006]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 105.0.5195.127
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 105.0.1343.53

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

**Comment by greenrobot-team** [comment] 2022-10-05 06:28
Alright, closing this then.

Can't find anything related in Flutter or Dart release notes.

Note the initial hunch that this is a tooling issue because VirusTotal reported problems with linking (`invalid-rich-pe-linker-version` tag) if this ever pops up again.

**Closed by greenrobot-team** 2022-10-05 06:28 UTC
