### ISSUE TITLE
Dependency conflict: objectbox_generator and mixpanel_flutter

### ISSUE THREAD

**Issue by eli1stark** [objectbox/objectbox-dart#666] opened 2024-08-27 05:12 UTC
### Description

We're experiencing a dependency conflict in our Flutter project involving `objectbox_generator` and `mixpanel_flutter`. The conflict stems from incompatible versions of the `js` package required by these dependencies.

### Current Setup

- `objectbox_generator`: 4.0.2
- `mixpanel_flutter`: 2.3.1

### Error Message

```
Because cryptography >=2.0.0 <2.1.0 depends on js ^0.6.3 and cryptography >=2.1.0 <2.6.0 depends on js ^0.6.2, cryptography >=2.0.0 <2.6.0 requires js ^0.6.2.
And because cryptography >=2.6.0 depends on js ^0.6.7, cryptography >=2.0.0 requires js ^0.6.2.
And because objectbox_generator 4.0.2 depends on cryptography ^2.0.5 and mixpanel_flutter >=2.3.0 depends on js ^0.7.1, objectbox_generator 4.0.2 is incompatible with mixpanel_flutter >=2.3.0.
So, because offsuit depends on both mixpanel_flutter 2.3.1 and objectbox_generator 4.0.2, version solving failed.
```

### Problem Analysis

1. `objectbox_generator` 4.0.2 depends on `cryptography ^2.0.5`
2. This version of `cryptography` requires `js ^0.6.2`
3. `mixpanel_flutter >=2.3.0` depends on `js ^0.7.1`
4. These requirements for `js` are incompatible

### Question

Is there a newer version of `objectbox_generator` that uses a more recent version of `cryptography`, which would be compatible with `js ^0.7.1`? If not, are there plans to update `objectbox_generator` to resolve this conflict?

### Additional Information

- Flutter version: [3.24.1 ]
- Dart version: [3.5.1]

### Possible Solutions

1. Update `objectbox_generator` to use a newer version of `cryptography`
2. Provide guidance on how to resolve this conflict in projects using both `objectbox_generator` and `mixpanel_flutter`

Thank you for your attention to this issue. Let me know if you need any additional information.

**Comment by greenrobot-team** [comment] 2024-08-27 08:03
Thanks for reporting! This is a duplicate of #638. There is a [workaround](https://github.com/objectbox/objectbox-dart/issues/638#issuecomment-2132908766).

**Closed by greenrobot-team** 2024-08-27 08:03 UTC
Labels: enhancement
