### ISSUE TITLE
Support for multiple views

### ISSUE THREAD

**Issue by eli1stark** [objectbox/objectbox-dart#540] opened 2023-06-02 04:56 UTC
Since Flutter 3.10, the Flutter team started to prepare support for multiple views and starts to deprecate single view APIs, it will be common for Flutter apps to support this as well in the future. At the moment ObjectBox allows only one view to interact with the database image, when 2nd view will try to access the database error will be thrown. This way if the app is using ObjectBox, it is locked to a single view and can't support multiple views.

Having multiple views is common nowadays, for example when you open app inside another app via dynamic link while you have main view running.

My proposal is to add ability to modify database from multiple views.

Additional information:
1. https://docs.flutter.dev/release/breaking-changes/window-singleton
2. https://www.youtube.com/watch?v=vtB-teu57vw

**Comment by greenrobot-team** [comment] 2023-06-05 09:28
Thanks for the heads-up! I have not looked at this deeply, but from a first impression is this possibly a duplicate of https://github.com/objectbox/objectbox-dart/issues/436#issuecomment-1465637666?

**Closed** 2023-06-06 05:44 UTC
Labels: enhancement
