### ISSUE TITLE
_QueryStringVectorProperty.notContains

### ISSUE THREAD

**Issue by frogman1189** [objectbox/objectbox-dart#260] opened 2021-06-02 05:23 UTC
I have an object that looks like

```
@Entity()
class Post {
  int id;
  List<String>? readByIds
  // other properties

  queryObject({this.id = 0, this.readByIds});
}
```

And I would like to be able to retrieve Posts I have not read. It would be useful if the generated metadata had the .notContains function for this kind of situation. i.e `box.query(Post_.notContains(userId))`

In my situation I know all the ids of who could read it, and so have added an extra property that is the inverse readByIds:
```
@Entity()
class Post {
  int id;
  List<String>? readByIds;
  List<String>? notReadByIds;
  // other properties

  queryObject({this.id = 0, this.readByIds, this.notReadByIds});
}
```
but the duplication makes this undesirable

**Comment by vaind** [comment] 2021-06-23 07:23
Will need to be implemented in the core. I'm raising a feature request there.

**Comment by vaind** [comment] 2021-06-23 07:28
BTW, this looks like a good candidate for a separate "table" with the list of which items have been read by which user (assuming that's what you mean by `readByIds`), e.g. 

```dart
@Entity()
class Post {
  int id;
  ...
}

@Entity()
class PostReads {
  int id;
  final post = ToOne<Post>();
  final user = ToOne<User>();
}
```

**Comment by greenrobot-team** [comment] 2024-02-28 07:28
As this is kind of asking for the `notOneOf` condition and to track interest in one place, closing this as a duplicate of #591.

**Closed by greenrobot-team** 2024-02-28 07:28 UTC
Labels: enhancement, on-hold
